### ISSUE TITLE
getting an error: nvim_err_writeln must not be called in a lua loop callback 

### ISSUE THREAD

**Issue by Rishabh672003** [Xuyuanp/neochat.nvim#1]
![image](https://user-images.githubusercontent.com/53911515/229287110-f77788a7-90f6-4034-9046-1d119e5ae8a0.png)

**Comment by Xuyuanp** [comment]
possibly been fixed. please update and try again.

**Comment by Rishabh672003** [comment]
Updated the plugin now am getting this error 
![image](https://user-images.githubusercontent.com/53911515/229367503-592534d0-2d40-497f-8fd2-b4f12d678211.png)

**Comment by Xuyuanp** [comment]
As the error described, you have to set an environment variable `OPENAI_API_KEY`

**Comment by Rishabh672003** [comment]
Yes i have set the env variable in zsh with `export OPENAI_KEY="MY-KEY"` am i doing anything wrong?

**Comment by Xuyuanp** [comment]
```diff
- export OPENAI_KEY='your-key'
+ export OPENAI_API_KEY='your-key'
```

**Comment by Rishabh672003** [comment]
that worked, thank you very much
